version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "weatherstation-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rhswm6yhkcs2"
s3_prefix = "weatherstation-dev"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
